version: "3.9"

networks:
  network_traefik_proxy:
    external: true
    
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    networks:
      - network_traefik_proxy
    volumes:
#      - /opt/docker/appdata/filebrowser:/config
      - /opt/docker/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /opt/docker/appdata/filebrowser/settings.json:/config/settings.json
      - /var/www:/srv
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=network_traefik_proxy"
      ## HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`files.aretz-online.de`)"
      - "traefik.http.routers.filebrowser-rtr.tls=true"
      - "traefik.http.routers.filebrowser-rtr.tls.certresolver=letsencrypt"
      ## Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-basic-auth@file"      # Basic Authentication
      #- "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"          # Google OAuth
      #- "traefik.http.routers.filebrowser-rtr.middlewares=chain-authelia@file,add-filebrowser" 
      #- "traefik.http.middlewares.add-filebrowser.addPrefix.prefix=/filebrowser"
      ## HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=80"

