version: "3.7"

services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: ${PUID}
      PGID: ${GUID}
      TZ: ${TZ}
    volumes:
      - "${DOCKERBASE_DIR}/appdata/homer/assets:/www/assets"
      - "${DOCKERBASE_DIR}/appdata/homer/assets:/www/config.yml"
    labels:
      - "traefik.enable=true"
